# Scale-Out Architecture Example
# https://inductiveautomation.com/ignition/architectures
# https://inductiveautomation.com/static/pdf/IgnitionArchitecture-ScaleOut.pdf
---
x-default-logging:
  &default-logging
  logging:
    options:
      max-size: '100m'
      max-file: '5'
    driver: json-file

x-ignition-opts:
  &ignition-opts
  <<: *default-logging
  image: inductiveautomation/ignition:${IGNITION_VERSION:-latest}
  env_file: gw-init/gateway.env
  secrets:
    - gateway-admin-password

services:
  gateway-fe:
    <<: *ignition-opts
    hostname: gateway-fe
    ports:
      - 8088:8088
    command: >
      -n Ignition-frontend
      -m ${GATEWAY_MAX_MEMORY:-512}
      -a gateway-fe.localtest.me
      -h 8088
      -s 8043
      -r /restore.gwbk
    environment:
      GATEWAY_NETWORK_REQUIRESSL: false
      GATEWAY_NETWORK_SECURITYPOLICY: SpecifiedList
      GATEWAY_NETWORK_WHITELIST: Ignition-tag1,Ignition-tag2
    volumes:
      - gateway-fe-data:/usr/local/bin/ignition/data
      - ./gw-backup:/backup
      - ./gw-init/gateway-fe.gwbk:/restore.gwbk

  gateway-tag1:
    <<: *ignition-opts
    hostname: gateway-tag1
    ports:
      - 8090:8088
    command: >
      -n Ignition-tag1
      -m ${GATEWAY_MAX_MEMORY:-512}
    environment:
      GATEWAY_NETWORK_0_HOST: gateway-fe
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: false
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
    volumes:
      - gateway-tag1-data:/usr/local/bin/ignition/data

  gateway-tag2:
    <<: *ignition-opts
    hostname: gateway-tag2
    ports:
      - 8092:8088
    command: >
      -n Ignition-tag2
      -m ${GATEWAY_MAX_MEMORY:-512}
    environment:
      GATEWAY_NETWORK_0_HOST: gateway-fe
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: false
      GATEWAY_ADMIN_PASSWORD_FILE: /run/secrets/gateway-admin-password
    volumes:
      - gateway-tag2-data:/usr/local/bin/ignition/data

  db:
    <<: *default-logging
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: ignition
      MARIADB_PASSWORD_FILE: /run/secrets/db-ignition-password
      MARIADB_DATABASE: ignition
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    secrets:
      - db-root-password
      - db-ignition-password
    volumes:
      - db-data:/var/lib/mysql
    
secrets:
  gateway-admin-password:
    file: secrets/gateway-admin-password
  db-ignition-password:
    file: secrets/db-ignition-password
  db-root-password:
    file: secrets/db-root-password

volumes:
  gateway-fe-data:
  gateway-tag1-data:
  gateway-tag2-data:
  db-data:
