# Enterprise Architecture Example
# https://inductiveautomation.com/ignition/architectures
# https://inductiveautomation.com/static/pdf/IgnitionArchitecture-Enterprise.pdf
---
x-default-logging:
  &default-logging
  logging:
    options:
      max-size: '100m'
      max-file: '5'
    driver: json-file

x-ignition-opts:
  &ignition-opts
  <<: *default-logging
  image: inductiveautomation/ignition:${IGNITION_VERSION:-latest}
  env_file: gw-init/gateway.env
  secrets:
    - gateway-admin-password

services:
  central-gw:
    <<: *ignition-opts
    hostname: central-gw
    ports:
      - 8088:8088
      - 8043:8043
    command: >
      -n Central
      -m ${GATEWAY_MAX_MEMORY:-512}
      -a central-gw.localtest.me
      -h 8088
      -s 8043
      -r base.gwbk
    environment:
      GATEWAY_NETWORK_REQUIRESSL: false
      GATEWAY_NETWORK_SECURITYPOLICY: SpecifiedList
      GATEWAY_NETWORK_WHITELIST: sitea,siteb
      EAM_SETUP_INSTALLSELECTION: Controller
      EAM_CONTROLLER_ARCHIVELOCATION: Manual
      EAM_CONTROLLER_ARCHIVEPATH: /eam-archive
      EAM_CONTROLLER_DATASOURCE: central
    networks:
      - corporate
      - sitea
      - siteb
    volumes:
      - central-gw-data:/usr/local/bin/ignition/data
      - ./eam-archive:/eam-archive
      - ./gw-init/central-gw.gwbk:/usr/local/bin/ignition/base.gwbk

  sitea-gw:
    <<: *ignition-opts
    hostname: sitea-gw
    ports:
      - 8089:8088
      - 8044:8043
    command: >
      -n SiteA
      -m ${GATEWAY_MAX_MEMORY:-512}
      -a sitea-gw.localtest.me
      -h 8089
      -s 8044
      -r base.gwbk
    environment:
      GATEWAY_NETWORK_REQUIRESSL: false
      GATEWAY_NETWORK_SECURITYPOLICY: SpecifiedList
      GATEWAY_NETWORK_WHITELIST: sitea-edge
      GATEWAY_NETWORK_0_HOST: central-gw
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: false
      GATEWAY_NETWORK_0_PINGRATE: 5000
      EAM_SETUP_INSTALLSELECTION: Agent
      EAM_AGENT_CONTROLLERSERVERNAME: Central
    networks:
      - corporate
      - sitea
    volumes:
      - sitea-gw-data:/usr/local/bin/ignition/data
      - ./gw-init/sitea-gw.gwbk:/usr/local/bin/ignition/base.gwbk

  sitea-edge:
    <<: *ignition-opts
    hostname: sitea-edge
    ports:
      - 8090:8088
      - 8045:8043
    command: >
      -n SiteA-Edge
      -m ${GATEWAY_MAX_MEMORY:-512}
      -a sitea-edge.localtest.me
      -h 8090
      -s 8045
      -r /usr/local/bin/ignition/base.gwbk
    environment:
      IGNITION_EDITION: edge
      GATEWAY_NETWORK_0_HOST: sitea-gw
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: false
      GATEWAY_NETWORK_0_PINGRATE: 5000
      EAM_SETUP_INSTALLSELECTION: Agent
      EAM_AGENT_CONTROLLERSERVERNAME: Central
    networks:
      - sitea
    volumes:
      - sitea-edge-data:/usr/local/bin/ignition/data
      - ./gw-init/sitea-edge.gwbk:/usr/local/bin/ignition/base.gwbk

  siteb-gw:
    <<: *ignition-opts
    hostname: siteb-gw
    ports:
      - 8091:8088
      - 8046:8043
    command: >
      -n SiteB
      -m ${GATEWAY_MAX_MEMORY:-512}
      -a siteb-gw.localtest.me
      -h 8091
      -s 8046
      -r /usr/local/bin/ignition/base.gwbk
    networks:
      - corporate
      - siteb
    environment:
      GATEWAY_NETWORK_0_HOST: central-gw
      GATEWAY_NETWORK_0_PORT: 8088
      GATEWAY_NETWORK_0_ENABLESSL: false
      GATEWAY_NETWORK_0_PINGRATE: 5000
      EAM_SETUP_INSTALLSELECTION: Agent
      EAM_AGENT_CONTROLLERSERVERNAME: Central
    volumes:
      - siteb-gw-data:/usr/local/bin/ignition/data
      - ./gw-init/siteb-gw.gwbk:/usr/local/bin/ignition/base.gwbk

  db:
    <<: *default-logging
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: ignition
      MARIADB_PASSWORD_FILE: /run/secrets/db-ignition-password
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db-root-password
    networks:
      corporate:
        aliases:
          - central-db
      sitea:
        aliases:
          - sitea-db
      siteb:
        aliases:
          - siteb-db
    secrets:
      - db-root-password
      - db-ignition-password
    volumes:
      - db-data:/var/lib/mysql
      - ./sql-init:/docker-entrypoint-initdb.d

networks:
  corporate:
  sitea:
  siteb:

secrets:
  gateway-admin-password:
    file: secrets/gateway-admin-password
  db-ignition-password:
    file: secrets/db-ignition-password
  db-root-password:
    file: secrets/db-root-password

volumes:
  central-gw-data:
  sitea-gw-data:
  sitea-edge-data:
  siteb-gw-data:
  db-data: